const $=id=>document.getElementById(id);
async function searchBooks(q){const r=await fetch('/api/search?q='+encodeURIComponent(q));if(!r.ok)throw Error('Backend search failed');return r.json()}
async function getLCSH(q){const r=await fetch('/api/lcsh?q='+encodeURIComponent(q));if(!r.ok)throw Error('LCSH service failed');return r.json()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function renderMatches(data){const list=$('matchList');list.innerHTML='';$('matchCount').textContent=(data.numFound||0)+' found';(data.docs||[]).forEach(b=>{const d=document.createElement('div');d.className='match';d.innerHTML=`<div><h3>${esc(b.title||'Untitled')}</h3><p>${esc((b.author_name||[]).join(', ')||'Author unknown')} • ${b.first_publish_year||'Year unknown'} • ${esc(b.source||'Catalog')}</p></div><button class="secondary">Analyze</button>`;d.querySelector('button').onclick=()=>showCatalog(b);list.appendChild(d)});if(!data.docs?.length)list.innerHTML='<div class="match"><div><h3>No matching records</h3><p>Try a different title or author spelling.</p></div></div>';$('matches').classList.remove('hidden')}
const rules=[
[/library|cataloging|cataloguing|librarianship|information science/,{subject:'Library & Information Science',ddc:'020',lcsh:['Libraries','Library science','Information science'],shelf:'000–099 • General Works / Library & Information Science'}],
[/computer|programming|software|information technology|ict|python|javascript|coding/,{subject:'Computer Science & Information Technology',ddc:'004–006',lcsh:['Computer science','Information technology'],shelf:'000–099 • General Works / Computing'}],
[/economics|finance|banking|business|accounting|entrepreneur|marketing/,{subject:'Economics / Business',ddc:'330',lcsh:['Economics','Finance','Business'],shelf:'300–399 • Social Sciences'}],
[/education|teaching|teacher|school|learning|curriculum/,{subject:'Education',ddc:'370',lcsh:['Education','Teaching'],shelf:'300–399 • Social Sciences'}],
[/psychology|behavior|behaviour|mental|personality/,{subject:'Psychology',ddc:'150',lcsh:['Psychology','Behavior'],shelf:'100–199 • Philosophy & Psychology'}],
[/self-help|success|motivation|personal development|leadership|achievement/,{subject:'Self-help / Personal Development',ddc:'158.1',lcsh:['Self-help techniques','Success','Personal development'],shelf:'100–199 • Philosophy & Psychology'}],
[/fiction|novel|poetry|poems|short stories|literature/,{subject:'Literature / Fiction',ddc:'800',lcsh:['Literature','Fiction'],shelf:'800–899 • Literature',type:'Fiction'}],
[/history|civilization|war|colonial|independence|historical/,{subject:'History',ddc:'900',lcsh:['History','Civilization'],shelf:'900–999 • History & Geography'}],
[/africa|kenya|kenyan|east africa|ethiopia|uganda|tanzania/,{subject:'Africa / Regional History',ddc:'960',lcsh:['Africa','Africa—History'],shelf:'900–999 • History & Geography'}],
[/religion|christian|church|bible|theology|islam|muslim/,{subject:'Religion',ddc:'200',lcsh:['Religion','Christianity'],shelf:'200–299 • Religion'}],
[/science|physics|chemistry|biology|astronomy/,{subject:'Science',ddc:'500',lcsh:['Science'],shelf:'500–599 • Science'}],
[/medicine|medical|health|nursing|disease|clinical/,{subject:'Medicine / Health',ddc:'610',lcsh:['Medicine','Health'],shelf:'600–699 • Technology / Medicine'}],
[/engineering|mechanical|electrical|civil engineering|construction/,{subject:'Engineering & Technology',ddc:'620',lcsh:['Engineering','Technology'],shelf:'600–699 • Technology'}]
];
function infer(text){const t=text.toLowerCase();const hit=rules.find(x=>x[0].test(t));return hit?hit[1]:{subject:'General / needs review',ddc:'—',lcsh:[],shelf:'Librarian review required'}}
function cleanDDC(values){if(!values?.length)return null;const x=String(values[0]).replace(/[^0-9.]/g,'');return x||null}
async function showCatalog(b){
 const text=[b.title,(b.subject||[]).join(' '),b.description,b.first_sentence].filter(Boolean).join(' ');const inf=infer(text);let ddc=cleanDDC(b.ddc)||inf.ddc;let subject=inf.subject;let lcsh=inf.lcsh||[];let shelf=inf.shelf;let confidence= b.ddc?.length?'Metadata-supported DDC • Review required':'Rule-based suggestion • Review required';
 const subjectTerms=[...(b.subject||[])].filter(Boolean).slice(0,12);if(subject==='General / needs review'&&subjectTerms.length)subject=subjectTerms.slice(0,3).join('; ');
 $('resultTitle').textContent=b.title||'Untitled';$('resultAuthor').textContent=(b.author_name||[]).join(', ')||'Author not supplied';$('materialType').textContent=inf.type||((ddc||'').startsWith('8')?'Fiction / Literature':'Non-fiction');$('subject').textContent=subject;$('ddc').textContent=ddc||'—';$('lcsh').textContent='Searching authoritative headings…';$('shelf').textContent=shelf;$('callNumber').textContent=ddc?ddc+' '+authorMark(b.author_name?.[0]):'—';$('source').textContent=b.source||'Bibliographic record';$('confidence').textContent=confidence;$('result').classList.remove('hidden');$('result').scrollIntoView({behavior:'smooth'});
 const lcshQuery=(inf.lcsh?.[0]||subjectTerms[0]||subject).replace(/[—–]/g,' ').trim();if(lcshQuery&&lcshQuery!=='General / needs review'){try{const data=await getLCSH(lcshQuery);if(data.headings?.length){lcsh=data.headings;confidence='LCSH candidates from Library of Congress • Review required'}$('lcsh').textContent=lcsh.length?lcsh.slice(0,5).join('; '):'No authoritative heading returned — review manually';$('confidence').textContent=confidence}catch(e){$('lcsh').textContent=lcsh.length?lcsh.join('; '):'Authority service unavailable — review manually'}}else $('lcsh').textContent=lcsh.length?lcsh.join('; '):'No LCSH candidate';
}
function authorMark(name){const clean=String(name||'').trim().split(/\s+/);const last=(clean[clean.length-1]||'').replace(/[^A-Za-z]/g,'');return (last||'XXX').slice(0,3).toUpperCase()}
$('searchBtn').onclick=async()=>{const q=$('query').value.trim();if(!q)return alert('Enter a title or author.');$('searchStatus').textContent='Searching real bibliographic records…';try{renderMatches(await searchBooks(q));$('searchStatus').textContent='Search complete. Select a record to generate cataloging suggestions.'}catch(e){$('searchStatus').textContent='Backend/API error. Make sure Flask is running and you have internet access.';console.error(e)}};$('query').onkeydown=e=>{if(e.key==='Enter')$('searchBtn').click()};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');const p=t.dataset.mode==='photo';$('searchMode').classList.toggle('hidden',p);$('photoMode').classList.toggle('hidden',!p)});
$('bookPhoto').onchange=e=>{const f=e.target.files[0];if(f)$('preview').innerHTML=`<img src="${URL.createObjectURL(f)}" alt="Book cover">`};$('photoAnalyzeBtn').onclick=async()=>{const f=$('bookPhoto').files[0];if(!f)return alert('Upload a book photo first.');$('ocrStatus').textContent='Reading image…';try{const {data:{text}}=await Tesseract.recognize(f,'eng');const q=text.split(/\n+/).filter(Boolean).slice(0,5).join(' ');if(!q)return $('ocrStatus').textContent='No readable text found.';$('ocrStatus').textContent='Text found. Searching…';$('query').value=q;$('searchBtn').click()}catch(e){$('ocrStatus').textContent='OCR failed. Try a clearer image.'}};
$('editBtn').onclick=()=>{document.querySelectorAll('#result strong').forEach(x=>x.contentEditable='true');alert('Fields are editable.');};$('approveBtn').onclick=()=>alert('Approved for this prototype.');
